FROM node:18-bullseye-slim

WORKDIR /app

RUN apt-get update && apt-get install --no-install-recommends -q -y htop inetutils-telnet net-tools

COPY *.json .
COPY yarn.lock .
COPY src/ ./src/
COPY public/ ./public/

RUN yarn install
RUN du -sh node_modules

RUN yarn build
RUN du -sh build

EXPOSE 3000

CMD [ "yarn", "start" ]
