// ++ //
def clusterHostMap = [
    'dev': '192.168.70.150',
    'stag': '',
    'prod': ''
]

def sshUserNameMap = [
    'dev': 'jenkinsuser',
    'stag': '',
    'prod': ''
]

def sshCredentialsMap = [
    'dev': '2a4c2063-ded7-4710-9247-2db45138d073',
    'stag': '',
    'prod': ''
]
//// ++//++//++//
def reactAppApiUrlMap = [
    'dev': 'https://linza.app/api/v1',
    'prod': ''
]
def reactAppCIMap = [
    'dev': 'false',
    'prod': ''
]

pipeline {
    environment {
        appName = 'lm-web'
        registry = "registry.gitlab.rifoxa.ru"
        registryCredentials = "rifoxa-registry-credentials"
        dockerImageName = "$env.registry" + "/linza-monitoring/deployment/" + "$env.appName" + ":" + "$BUILD_NUMBER"
        kubernetesNamespace = "default"
    }

    parameters {
        choice(name: 'BUILD_ENV', choices: ['dev', 'stag', 'prod'], description: 'Build environment')
    }

    agent any

    stages {
        stage('Clone repository') {
            /* Let's make sure we have the repository cloned to our workspace */
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                nodejs(nodeJSInstallationName: 'Node.js-18') {
                    sh 'npm config ls'
                    sh 'npm install --force'
                }
            }
        }

        stage('Build Application'){
            steps {
                script {
                    def VITE_API_URL = reactAppApiUrlMap."$BUILD_ENV"
                    def CI = reactAppCIMap."$BUILD_ENV"
                    nodejs(nodeJSInstallationName: 'Node.js-18') {
                        sh "VITE_API_URL=$VITE_API_URL CI=$CI npm run build"
                    }
                }
            }
        }

        stage('Build image') {
           /* This builds the actual image; synonymous to
            * docker build on the command line */
            steps {
                script {
                    echo "Registry for current build: $env.registry"
                    app = docker.build( dockerImageName )
                }
            }
        }

        stage('Push image') {
           /* Pushing the image with two tags:
            * First, the incremental build number from Jenkins
            * Second, the 'latest' tag.
            * Pushing multiple tags is cheap, as all the layers are reused. */
            steps {
                script {
                    docker.withRegistry("https://$env.registry", registryCredentials) {
                        app.push()
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Check K8s cluster') {
            steps {
                script {
                    def clusterCheck = "whoami && KUBECONFIG=/home/${sshUserNameMap."$BUILD_ENV"}/.kube/config && \
                        kubectl get pods && helm list"
                    
                    sshagent(credentials: [sshCredentialsMap."$BUILD_ENV"]) {
                        sh "ssh -o StrictHostKeyChecking=no ${sshUserNameMap."$BUILD_ENV"}@${clusterHostMap."$BUILD_ENV"} '${clusterCheck}' "
                    }
                }
            }
        }
        stage('Copy Helm configs to K8s cluster') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: sshCredentialsMap."$BUILD_ENV", keyFileVariable: 'key')]) {
                        def remote = [:]
                        remote.name = clusterHostMap."$BUILD_ENV"
                        remote.host = clusterHostMap."$BUILD_ENV"
                        remote.user = sshUserNameMap."$BUILD_ENV"
                        remote.identityFile = key
                        remote.allowAnyHosts = true
                        remote.failOnError = true

                        sshPut remote: remote, from: "./helm", into: "/home/${sshUserNameMap."$BUILD_ENV"}/"
                    }
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                script {
                    docker.withRegistry("https://$env.registry", registryCredentials) {
                        def helmUpgrade = "KUBECONFIG=/home/${sshUserNameMap."$BUILD_ENV"}/.kube/config && \
                            helm upgrade \
                            --set buildNumber=$BUILD_NUMBER \
                            --set registryAddress=$env.registry \
                            $env.appName ./helm/$env.appName-chart --install"
                        
                        sshagent(credentials: [sshCredentialsMap."$BUILD_ENV"]) {
                            sh "ssh -o StrictHostKeyChecking=no ${sshUserNameMap."$BUILD_ENV"}@${clusterHostMap."$BUILD_ENV"} '${helmUpgrade}' "
                        }
                    }
                }
            }
        }

        stage('Post-clean') {
            steps {
                script {
                    try{
                        def kubernetesRollout = "KUBECONFIG=/home/${sshUserNameMap."$BUILD_ENV"}/.kube/config && \
                            kubectl rollout status deployment $env.appName --namespace=$env.kubernetesNamespace --watch=true"
                        
                        sshagent(credentials: [sshCredentialsMap."$BUILD_ENV"]) {
                            sh "ssh -o StrictHostKeyChecking=no ${sshUserNameMap."$BUILD_ENV"}@${clusterHostMap."$BUILD_ENV"} '${kubernetesRollout}' "
                        }
                    } catch(error) {
                        echo "!!! Roll out update failed"
                        echo "!!! Executing rollout undo"
                        def kubernetesRolloutUndo = "KUBECONFIG=/home/${sshUserNameMap."$BUILD_ENV"}/.kube/config && \
                            kubectl rollout undo deployments/$env.appName --namespace=$env.kubernetesNamespace"
                        
                        sshagent(credentials: [sshCredentialsMap."$BUILD_ENV"]) {
                            sh "ssh -o StrictHostKeyChecking=no ${sshUserNameMap."$BUILD_ENV"}@${clusterHostMap."$BUILD_ENV"} '${kubernetesRolloutUndo}' "
                        }
                        error "!!! Deployment of latest build failed!"
                    }
                    sh "docker image rm $env.dockerImageName"
                    sh "docker builder prune -f -a"
                }
            }
        }
    }
}

