apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
spec:
  rules:
  - host: k8s-node2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: lm-web-service
              port:
                number: 80
